### ISSUE TITLE
N = err.decode("utf-8").split(" of ")[1] fails

### ISSUE THREAD

**Issue by zhaozj89** [BlGene/egl_check#2]
Hi, thanks for this work. I would like to inquire about a problem. I followed the readme, and ran `list_egl_options.py`. But it reported index out of range [here](https://github.com/BlGene/egl_check/blob/master/list_egl_options.py#L13). I guess that my machine cannot load EGL correctly. 

I use a Ubuntu 16.04 sever with a Nvidia 2080Ti card, and the driver is `nvidia-container-runtime 3.5.0-1` and cuda is `11.2`. I have searched the Internet for a while, such as installing mesa as `sudo apt-get install libglfw3-dev libgles2-mesa-dev`. But it still does not work. I also found your thread [here](https://github.com/bulletphysics/bullet3/issues/3028), and ran `ldconfig -p | grep EGL` and got:

        libEGL.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/mesa-egl/libEGL.so.1
	libEGL.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libEGL.so
	libEGL.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/mesa-egl/libEGL.so

I really want to make EGL work in pybullet, and would like to inquire if you know anything to fix this. Thanks very much.

**Comment by BlGene** [comment]
@zhaozj89 

I have not looked at this stuff in a while, but I will try to answer as best as possible. The error in the `list_egl_options.py` script is probably caused by the parsing failing. You could run the `./EGL_options.o` command by itself and report it's output. 

I think the problem is that the nvidia EGL libraries are not being found, my `ldconfig -p | grep EGL` looks like this:
```        libEGL_nvidia.so.0 (libc6,x86-64) => /lib/x86_64-linux-gnu/libEGL_nvidia.so.0
        libEGL_nvidia.so.0 (libc6) => /lib/i386-linux-gnu/libEGL_nvidia.so.0
        libEGL_mesa.so.0 (libc6,x86-64) => /lib/x86_64-linux-gnu/libEGL_mesa.so.0
        libEGL.so.1 (libc6,x86-64) => /lib/x86_64-linux-gnu/libEGL.so.1
        libEGL.so (libc6,x86-64) => /lib/x86_64-linux-gnu/libEGL.so
```
If you look at your installed nvidia packages `apt list --installed | grep nvidia` you should see `libnvidia-gl`. If not try to re-do the installation of the ubuntu nvidia packages.

**Comment by zhaozj89** [comment]
Thanks. Yes, it is that the nvidia EGL libraries are not being found. I remembered that I read a thread before that nvidia runtime driver does not have EGL. Anyway, I will try to re-install nvidia packages. Thanks very much.
